// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1) {
  return window['go']['main']['App']['CreateWallet'](arg1);
}

export function ExportPrivateKey() {
  return window['go']['main']['App']['ExportPrivateKey']();
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetNodeURL() {
  return window['go']['main']['App']['GetNodeURL']();
}

export function GetTransactionHistory() {
  return window['go']['main']['App']['GetTransactionHistory']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasWallet() {
  return window['go']['main']['App']['HasWallet']();
}

export function IsEncrypted() {
  return window['go']['main']['App']['IsEncrypted']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function LoadWallet(arg1) {
  return window['go']['main']['App']['LoadWallet'](arg1);
}

export function LockWallet() {
  return window['go']['main']['App']['LockWallet']();
}

export function SendTransaction(arg1, arg2) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2);
}

export function SetNodeURL(arg1) {
  return window['go']['main']['App']['SetNodeURL'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
