// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateWallet(arg1:string):Promise<main.WalletInfo>;

export function ExportPrivateKey():Promise<string>;

export function GetAddress():Promise<string>;

export function GetBalance():Promise<main.BalanceInfo>;

export function GetNodeURL():Promise<string>;

export function GetTransactionHistory():Promise<Array<main.TransactionInfo>>;

export function GetVersion():Promise<string>;

export function HasWallet():Promise<boolean>;

export function IsEncrypted():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function LoadWallet(arg1:string):Promise<main.WalletInfo>;

export function LockWallet():Promise<void>;

export function SendTransaction(arg1:string,arg2:string):Promise<main.TxResult>;

export function SetNodeURL(arg1:string):Promise<void>;

export function TestConnection():Promise<main.NodeStatus>;
